name: GameModeClassic
version: '${project.version}'
main: jp.mrik.gamemodeclassic.GameModeClassic
api-version: 1.16
authors: [ Mr_IK ]
description: GameModeClassic
commands:
  gamemode:
    description: GameModeClassic
    usage: /<command>
    default: op